force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <inlineHelpText>Time remaining to resolve the issue</inlineHelpText>
    <label>SLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Urgency__c.field-meta.xml
<CustomField>
    <fullName>Urgency__c</fullName>
    <label>Urgency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
                <isActive>false</isActive>
                <label>Incident</label>
            </value>
            <value>
                <fullName>Incident;Average</fullName>
                <isActive>false</isActive>
                <label>Incident;Average</label>
            </value>
            <value>
                <fullName>Incident;High</fullName>
                <isActive>false</isActive>
                <label>Incident;High</label>
            </value>
            <value>
                <fullName>Incident;Low</fullName>
                <isActive>false</isActive>
                <label>Incident;Low</label>
            </value>
            <value>
                <fullName>Preventive;Average</fullName>
                <isActive>false</isActive>
                <label>Preventive;Average</label>
            </value>
            <value>
                <fullName>Preventive;High</fullName>
                <isActive>false</isActive>
                <label>Preventive;High</label>
            </value>
            <value>
                <fullName>Problem;Low</fullName>
                <isActive>false</isActive>
                <label>Problem;Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testQueueableAtualizaSLA.cls
@isTest
public class testQueueableAtualizaSLA {
    @IsTest
    static void executeTest(){

         Case cc = New Case(
            Description = 'Teste',
            Subject = 'Teste',
            Urgency__c = 'Average',
            Category__c = 'Internet',
            Type = 'Preventive',
            Email__c = 'teste@gmail.com.br',
            Name__c =  'Teste',
            Surname__c = 'Teste'
        );

        insert cc;

        Test.startTest();
            System.enqueueJob(new CalcSLA());
        Test.stopTest();

        Case updated = [SELECT Id, SLA__c FROM Case WHERE Id = :cc.Id];
        System.assertNotEquals(10, updated.SLA__c);
    }
}